name: Telegram Notification

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.SM_SEAN }}
        token: ${{ secrets.SM_SEAN_TOKEN }}
        args: There has been a ${{ github.event_name }} event recently from ${{ github.actor }}.