name: Telegram Notification

on: [ push, pull_request ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.GC_TEST }}
        token: ${{ secrets.SM_SEAN_TOKEN }}
        args: ${{ github.actor }} has made a ${{ github.event_name }} event in ${{ github.ref }} recently. You can visit this change at ${{ github.server_url }}/seannich/ETI_Exercise_7_and_8/commit/${{ github.sha }} 